// import banner_G105 from '@/assets/newImages/banner_G105.png';
// import banner_V5 from '@/assets/newImages/banner_V5.png';
// import banner_G050 from '@/assets/newImages/banner_G050.png';
// import banner_T from '@/assets/newImages/banner_T.png';
// import banner_V9 from '@/assets/newImages/banner_V9.png';

// import vehicle1_1 from '@/assets/newImages/vehicle1_1.jpg';
// import vehicle1_2 from '@/assets/newImages/vehicle1_2.jpg';
// import vehicle1_3 from '@/assets/newImages/vehicle1_3.jpg';
// import vehicle1_4 from '@/assets/newImages/vehicle1_4.jpg';

import { getEnv } from '@/utils/env';

export const CDNUrl = getEnv() === 'development' ? "https://pub-ef972d7a1bcc47888d714e9a2dd3c88b.r2.dev" : "https://assets.senseautos.com";
// dev时  CDNUrl也可以用/resource

export const menuTree = [
  // {
  //   "title": "Vehicles",
  //   "name": "Vehicles",
  //   "description": "",
  //   "pId": "0",
  //   "id": "A2000",
  //   "inMenu": "1",
  //   "path": "/vehicles?id=A2000001",
  //   "children": [
  //     {
  //       "title": "WuLing D5",
  //       "name": "WuLing D5",
  //       "description": "",
  //       "pId": "A2000",
  //       "id": "A2000001",
  //       "inMenu": "1",
  //       "path": "/vehicles?id=A2000001",
  //       "active": false,
  //       "banners": [],
  //     },
  //     {
  //       "title": "WuLing A7",
  //       "name": "WuLing A7",
  //       "description": "",
  //       "pId": "A2000",
  //       "id": "A2000002",
  //       "inMenu": "1",
  //       "path": "/vehicles?id=A2000002",
  //       "active": false,
  //       "banners": [],
  //     },
  //     {
  //       "title": "DongFengQ8",
  //       "name": "DongFengQ8",
  //       "description": "",
  //       "pId": "A2000",
  //       "id": "A2000003",
  //       "inMenu": "1",
  //       "path": "/vehicles?id=A2000003",
  //       "active": false,
  //       "banners": [],
  //     },
  //     {
  //       "title": "DongFengR5",
  //       "name": "DongFengR5",
  //       "description": "",
  //       "pId": "A2000",
  //       "id": "A2000003",
  //       "inMenu": "1",
  //       "path": "/vehicles?id=A2000003",
  //       "active": false,
  //       "banners": [],
  //     },
  //   ],
  // },
  // {
  //   "title": "services",
  //   "name": "services",
  //   "description": "",
  //   "pId": "0",
  //   "id": "A2001",
  //   "inMenu": "1",
  //   "path": "/services",
  //   "children": [
  //     {
  //       "title": "服务特色",
  //       "name": "服务特色",
  //       "description": "",
  //       "pId": "A2001",
  //       "id": "A2001001",
  //       "inMenu": "1",
  //       "path": "/services",
  //       "active": false,
  //       "banners": [],
  //     },
  //     {
  //       "title": "几大服务市场",
  //       "name": "几大服务市场",
  //       "description": "",
  //       "pId": "A2001",
  //       "id": "A2001002",
  //       "inMenu": "1",
  //       "path": "/services",
  //       "active": false,
  //       "banners": [],
  //     },
  //     {
  //       "title": "合作站点",
  //       "name": "合作站点",
  //       "description": "",
  //       "pId": "A2001",
  //       "id": "A2001003",
  //       "inMenu": "1",
  //       "path": "/services",
  //       "active": false,
  //       "banners": [],
  //     },
  //   ],
  // },
  {
    "title": "Home",
    "name": "Home",
    "description": "",
    "pId": "0",
    "id": "A2001",
    "inMenu": "1",
    "path": "/",
  },
  // {
  //   "title": "News",
  //   "name": "News",
  //   "description": "",
  //   "pId": "0",
  //   "id": "A2002",
  //   "inMenu": "1",
  //   "path": "/news",
  // },
  {
    "title": "About Us",
    "name": "About Us",
    "description": "",
    "pId": "0",
    "id": "A2003",
    "inMenu": "1",
    "path": "/#about_us",
    "children": [
      // {
      //   "title": "History",
      //   "name": "History",
      //   "description": "",
      //   "pId": "A2003",
      //   "id": "A2003001",
      //   "inMenu": "1",
      //   "path": "/aboutus#history",
      //   "active": false,
      //   "banners": [],
      // },
      // {
      //   "title": "Menbers",
      //   "name": "Menbers",
      //   "description": "",
      //   "pId": "A2003",
      //   "id": "A2003002",
      //   "inMenu": "1",
      //   "path": "/aboutus#members",
      //   "active": false,
      //   "banners": [],
      // },
      // {
      //   "title": "Contact",
      //   "name": "Contact",
      //   "description": "",
      //   "pId": "A2003",
      //   "id": "A2003003",
      //   "inMenu": "1",
      //   "path": "/aboutus",
      //   "active": false,
      //   "banners": [],
      // },
    ],
  },
];
export const bannerListData = [
  {
    title: '轮播图5',
    img: CDNUrl + '/images/banner_V9.png',
    docUrl: CDNUrl + '/doc/V9.png',
    videoUrl: CDNUrl + '/video/V9.mp4',
    content: '',
  },
  {
    title: '轮播图4',
    img: CDNUrl + '/images/banner_T.png',
    docUrl: CDNUrl + '/doc/T.png',
    videoUrl: CDNUrl + '/video/T.mp4',
    content: '',
  },
  {
    title: '轮播图2',
    img: CDNUrl + '/images/banner_V5.png',
    docUrl: CDNUrl + '/doc/V5.png',
    videoUrl: CDNUrl + '/video/V5.mp4',
    content: '',
  },
  {
    title: '轮播图3',
    img: CDNUrl + '/images/banner_G050.png',
    docUrl: CDNUrl + '/doc/G050.pdf',
    videoUrl: CDNUrl + '/video/G050.mp4?v=1.0',
    content: '',
  },
  {
    title: '轮播图1',
    img: CDNUrl + '/images/banner_G105.png',
    docUrl: CDNUrl + '/doc/G105.pdf',
    videoUrl: CDNUrl + '/video/G105.mp4',
    content: '',
  },
];
export const vehiclesBanner = [
  {
    title: 'Van',
    // img: vehicle1_1,
    content: '',
  },
  {
    title: 'Cab',
    // img: vehicle1_2,
    content: '',
  },
  {
    title: '4X4',
    // img: vehicle1_3,
    content: '',
  },
  {
    title: 'CNG',
    // img: vehicle1_4,
    content: '',
  }
];
export const newsListData = [
  {
    id: '001',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动1',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    image: "https://www.gwdg.com.cn/js/userfiles/fileupload/202501/1882739520616202240.jpg",
    content: '<p style="line-height: 2;">&nbsp;</p><p style="text-indent: 32pt; text-align: justify; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;" align="justify"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">5月9日，广西水发集团举行2025年青年职工座谈会暨青年突击队授旗仪式，倾听青年建言献策和成长诉求，号召青年以实干担当投身八桂水网建设。集团党委书记、董事长闫九球出席会议，与青年代表面对面交流，对青年成长发展提出殷切期望。集团党委副书记、纪委书记、职工董事、工会主席刘春元主持会议，在家集团领导班子成员参加会议。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;" align="justify"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924648677193326592.jpg" width="700" height="474" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">座谈会上，来自不同领域、不同岗位的8名青年代表结合岗位实际、个人成长经历，用&ldquo;青言青语&rdquo;分享了参与集团改革发展的生动实践、个人的成长感悟、取得的工作成绩等，围绕集团高质量发展畅谈工作设想和意见建议。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">闫九球代表集团党委向广大团员青年致以节日的问候和诚挚的祝福，并带领青年职工深入学习习近平总书记重要讲话和给谢依特小学戍边支教西部计划志愿者服务队队员回信精神，围绕学习贯彻习近平总书记关于青年工作的重要论述，向水发青年提出殷切期望。他寄语青年，继续弘扬五四精神，以青春姿态书写不负时代的新答卷：一要志存高远，胸怀&ldquo;国之大者&rdquo;，将个人理想融入集团高质量发展和新时代水利事业；二要敢想敢干、挺膺担当，在环北广西工程等重大项目中打头阵、当先锋；三要孜孜以求、学思践悟，用习近平新时代中国特色社会主义思想武装头脑，向前辈先进学习，在实践锻炼中长本领、增才干；四要树牢治水为民思想，深入基层、脚踏实地，身上有土、脚上有泥，才能心中有数、眼中有光；五要以开展深入贯彻中央八项规定精神学习教育为契机，强化纪律意识和规矩意识，加强作风建设，争做清正廉洁的先锋表率。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924648859700076544.jpg" width="700" height="483" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">闫九球为4支青年突击队代表授旗。授旗现场，青年突击队队员代表发出倡议，号召广大青年突击队员坚持党旗所指就是团旗所向，争当高举旗帜、挺膺担当的践行者，争当广西水利建设的突击队，争做集团高质量发展的生力军。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团人力部、党群部主要负责人，各二级企业主要负责人、分管青年工作的领导，人力部、党群部主要负责人，以及线上线下青年职工共80余人参加座谈会。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">&nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">水发青年之声</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团审计风控部副经理 蓝卓钰<img style="display: block; margin-left: auto; margin-right: auto;" src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924649196771123200.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">作为青年职工，肩负着传承与创新的双重使命。我们要牢记习近平总书记对广大青年殷切期望，坚定理想信念，厚植家国情怀，练就过硬本领，发扬奋斗精神。我们要充分发挥青年的探索勇气和进取动力，知重负重，克难而进，面对新技术、新挑战，敢于创新、勇于开拓，将创新与实践相结合，以创新思维和创新方法推动工作取得新成效，为可能，尽所能，努力为集团高质量发展注入源源不断的活力。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">广西水电设计院水工院副院长&nbsp;陆蓝翔</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924654437029683200.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">&ldquo;宝剑锋从磨砺出，梅花香自苦寒来&rdquo;，青年员工想在水利战线建功立业，必须清醒认识到：成长之路从来不会一帆风顺，唯有在心理上&ldquo;未雨绸缪&rdquo;，在行动上&ldquo;厉兵秣马&rdquo;，方能在大浪淘沙中淬炼成金。在推动集团做强做优做大中，主动请缨，在遇到技术瓶颈、知识盲区的情况下，以攻坚姿态迎难而上，敢担当，有作为，让拼搏奋斗成为青春最亮丽的底色，在时代答卷上，写下无愧于心的青春篇章。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">广西水电设计院数字化院研发三所所长&nbsp;陆彬</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655311470764032.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">青年是科技创新的生力军。面对智慧水利的广阔蓝海，我们既要深耕专业，更要跳出&ldquo;舒适圈&rdquo;，在跨界融合中寻找突破。尤其在人工智能与水利深度融合的实践中，唯有将&ldquo;理论建模&rdquo;与&ldquo;场景应用&rdquo;深度结合，才能让人工智能从实验室走向江河湖库，才能让技术真正落地生花。青年干部当以&ldquo;本领恐慌&rdquo;的紧迫感，主动拥抱新技术、新业态，让&ldquo;数字基因&rdquo;成为水利高质量发展的新引擎。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">广西水电设计院规划院规划三所副所长&nbsp;唐珊</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655400033492992.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">我们青年水利人必须勇立潮头，以时不我待的使命感，积极拥抱人工智能、大数据分析等新领域，以新科技、新技术助力提高工作效率，为工程前期决策提供精准数据支撑；&ldquo;向外求索、向内自省&rdquo;，我们既要积极汲取行业前沿知识，也要时常审视自身不足。面对更繁重的工作任务与复杂项目，我们要以&ldquo;功成不必在我，功成必定有我&rdquo;的担当，在重大水利工程前期推进中勇挑重担，以饱满的热情和扎实的专业素养，攻克每一个技术难关，为集团高质量发展建言献策、添砖加瓦。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">环北公司建设管理部副主任、南宁片区建设现场指挥部</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">工程技术科负责人&nbsp;黄展案</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655481172303872.jpg" width="349" height="349" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">在日常工作中，从施工组织设计审查到现场安全质量监督，从进度款审核到技术难题攻关，我们深知：每一项数据、每一道工序，都关乎工程成败，更关乎民生福祉。环北广西工程是广西水网的&ldquo;大动脉&rdquo;，我们青年必须用专业与责任，确保每一寸管道安全、每一座泵站高效，为壮乡人民打造百年精品工程！</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">环北公司计划合同部副主任、钦州片区建设现场指挥部</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">合同管理科负责人&nbsp;彭高著</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655561673580544.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">作为青年员工，我们是业务骨干，肩负着实际工作中的重要责任。任何事情如果不去落实，都会变成巨大的困难。就像我们建管系统中密密麻麻的流程节点，初看令人望而生畏，但只要我们每一位员工都以主人翁的精神主动作为、迎难而上，积极疏通、解决问题，就没有克服不了的困难。正所谓&ldquo;道阻且长，行则将至&rdquo;。水发集团因水而生、因水而兴，作为新时代的青年，更应主动担当，在推动工程高质量建设中贡献青春力量，这既是责任，更是我们的光荣使命。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">水发数科运维管理部职员&nbsp;唐川松</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655640320974848.jpg" width="350" height="350" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">在数字时代，信息优势决定发展先机。水发青年当紧扣科技脉搏，以开放姿态推动人工智能、物联网、数字孪生、机器人等前沿技术与水利工程融合。我们以建设环北广西工程信息化（EPC）项目为契机，同步推进集团信创云计算数据中心建设，着力构建自主可控的信创数字底座，谋划打造集&ldquo;感-传-知-用&rdquo;全链条的水发特色智慧水利体系，全面提升广西水网智慧化调度效能。</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">水发商贸办公室职员&nbsp;王佳琳</span></p><p style="margin: 0pt 0pt 0.0001pt; text-indent: 0pt; text-align: center; line-height: 2; font-family: 等线; font-size: 10.5pt;" align="center"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;"><img src="https://www.gwdg.com.cn/js/userfiles/fileupload/202505/1924655722818740224.jpg" width="349" height="349" /></span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">理想信念是人生的灯塔，我们对未来的憧憬，对事业的热爱，对责任的担当，都源于坚定的理想信念。当前，广西水利事业处于&ldquo;现代化水网建设全面落地&rdquo;与&ldquo;高质量发展深度攻坚&rdquo;并行的关键阶段&zwnj;，广西水发集团作为广西水网建设的&ldquo;主力军&rdquo;，赋予了我们施展才干的广阔平台。水发青年们怀揣着积极向上的心态，不断追求自我提升和成长，始终以饱满的热情立足本职岗位，开拓进取，突破创新，努力为更高远的目标奋斗，不断实现个人价值与集团目标的协同发展。</span></p>',
    weight: 0,
  },
  {
    id: '002',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动2',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    image: "https://www.gwdg.com.cn/js/userfiles/fileupload/202501/1882739520616202240.jpg",
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
    weight: 0,
  },
  {
    id: '003',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动3',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '004',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动4',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '005',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动5',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '006',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动6',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '007',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动7',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '008',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动8',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '009',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动9',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '010',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动10',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '011',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动11',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
  {
    id: '012',
    title: '追寻无名英雄足迹 凝聚奋进力量——广西水发集团开展“岂曰无名 山河为证”主题参观活动12',
    description: '为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观“岂曰无名 山河为证”党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。',
    createDate: "2025-09-11 10:02",
    weight: 0,
    content: '<p>&nbsp;</p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">为纪念中国人民抗日战争暨世界反法西斯战争胜利80周年，深化爱国主义教育，9月11日，集团组织党员、职工赴广西民族博物馆，参观&ldquo;岂曰无名 山河为证&rdquo;党的隐蔽战线主题展览，通过沉浸式学习重温革命历史，汲取奋进力量。</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">展览分为四大板块，系统呈现了抗战时期隐蔽战线工作者&ldquo;以生命为墨、以信仰为笔&rdquo;的不朽史诗。在&ldquo;获取日伪战略性内幕性情报&rdquo;展区，泛黄的密电手稿与历史实物生动再现了情报人员深入虎穴的惊险历程；而&ldquo;保卫延安和抗日根据地&rdquo;部分则通过珍贵影像，展现了无名英雄们&ldquo;干惊天动地事，做隐姓埋名人&rdquo;的崇高品格。集团职工驻足凝视，低声交流，被革命先辈&ldquo;于无声处听惊雷&rdquo;的胆识与忠诚深深震撼。青年党员董磊感慨道：&ldquo;先辈们用信仰照亮黑暗，我们更应以实干<span style="color: #000000; white-space: normal; background-color: #ffffff; float: none; display: inline;">​</span><span style="border-width: 0px; font-stretch: inherit; line-height: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: #000000; white-space: normal; background-color: #ffffff;">​传承信仰</span> ，让&lsquo;无名精神&rsquo;在推进环北广西工程建设、推动集团高质量发展中发光发热。&rdquo;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">集团党员、职工纷纷表示，将以此次参观为契机，把隐蔽战线&ldquo;忠诚、奉献、智慧、担当&rdquo;的精神内核融入工作实践，加快推进重大水利工程建设，为广西高质量发展贡献水发力量。&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p><p style="text-indent: 32pt; line-height: 2; margin: 0pt 0pt 0.0001pt; font-family: Calibri; font-size: 10.5pt; text-align: right;"><span style="font-family: ＇Microsoft YaHei＇; font-size: 14pt;">（文/集团办公室 周怿杰）</span></p>',
  },
]