import { getAppEnvConfig } from '@/utils/env';
const { CDN_URL } = getAppEnvConfig();

export default [
  {
    "id": 'e-Van',
    "name": 'e-Van',
    "menuType": 'group',
    "children": [
      {
        "id": "E-STAR_V9",
        "name": 'E-STAR V9',
        "type": "Big Van",
        "size": "5995*2036*2590",
        "GVW": "3.5T",
        "Battery": "100.96kWh",
        "Range": "300km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_V9.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_V9.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_V9.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_V9.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_V9.webp`,
        "videoSrc": `${CDN_URL}/resource/video/V9.mp4`,
      },
      {
        "id": "E-STAR_V5",
        "name": 'E-STAR V5',
        "type": "Medium Van",
        "size": "5270*1730*1980",
        "GVW": "3.0T",
        "Battery": "41.86kWh",
        "Range": "260km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_V5.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_V5.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_V5.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_V5.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_V5.webp`,
        "videoSrc": `${CDN_URL}/resource/video/V5.mp4`,
      },
      {
        "id": "G105-3",
        "name": 'G105-3',
        "type": "Medium Van",
        "size": "4525*1610*190",
        "GVW": "2.5T",
        "Battery": "41.86kWh",
        "Range": "252km",
        "slideImg": `${CDN_URL}/resource/products/slide_G105-3.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G105-3.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G105-3.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G105-3.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G105.mp4`,
      },
      {
        "id": "G050-L",
        "name": 'G050-L',
        "type": "Small Van",
        "size": "3395*1475*1950",
        "GVW": "1.67T",
        "Battery": "29.67kWh",
        "Range": "162km",
        "slideImg": `${CDN_URL}/resource/products/slide_G050-L.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G050-L.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G050-L.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G050-L.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G050.mp4`,
      },
    ]
  },
  {
    "id": 'e-Light_Truck',
    "name": 'e-Light Truck',
    "menuType": 'group',
    "children": [
      {
        "id": "E-STAR_T",
        "name": 'E-STAR T',
        "type": "Medium Truck",
        "size_with_box": "5750*1770*2670",
        "size_chassis": "5500*1650*1750",
        "GVW": "3.5T",
        "Battery": "66.8kWh",
        "Range": "250km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_T.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_T.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_T.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_T.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_T.webp`,
        "videoSrc": `${CDN_URL}/resource/video/T.mp4`,
      },
      {
        "id": "G050P-L",
        "name": 'G050P-L',
        "type": "Small Van",
        "size": "3695*1475*1980",
        "GVW": "1.6T",
        "Battery": "29.67kWh",
        "Range": "210km",
        "slideImg": `${CDN_URL}/resource/products/slide_G050P-L.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G050P-L.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G050P-L.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G050P-L.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G050.mp4`,
      },
    ]
  },
  {
    "id": 'e-Tractor',
    "name": 'e-Tractor',
    "menuType": 'group',
    "children": [
      {
        "id": "Sany_SE636",
        "name": 'Sany SE636',
        "type": "e-Tractor",
        "size": "6890*2545*3870",
        "Battery": "636kWh",
        "Range": "500km",
        "L2": "AEB/LKA/LCC/LDW/FCW/DMS/360° Camera ",
        "slideImg": `${CDN_URL}/resource/products/slide_Sany_SE636.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_Sany_SE636.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_Sany_SE636.webp`,
        "formImg": `${CDN_URL}/resource/products/product_Sany_SE636.webp`,
        "videoSrc": `${CDN_URL}/resource/video/Sany_SE636.mp4`,
      },
    ]
  },
];