import { getAppEnvConfig } from '@/utils/env';
const { CDN_URL } = getAppEnvConfig();

export default [
  {
    "id": 'e-Van',
    "name": 'e-Van',
    "menuType": 'group',
    "children": [
      {
        "id": "E-STAR_V9",
        "name": 'E-STAR V9',
        "type": "Big Van",
        "size": "5995*2036*2590",
        "GVW": "3.5T",
        "Battery": "100.96kWh",
        "Range": "300km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_V9.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_V9.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_V9.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_V9.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_V9.webp`,
        "videoSrc": `${CDN_URL}/resource/video/V9.mp4`,
      },
      {
        "id": "E-STAR_V5",
        "name": 'E-STAR V5',
        "type": "Medium Van",
        "size": "5270*1730*1980",
        "GVW": "3.0T",
        "Battery": "41.86kWh",
        "Range": "260km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_V5.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_V5.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_V5.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_V5.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_V5.webp`,
        "videoSrc": `${CDN_URL}/resource/video/V5.mp4`,
      },
      {
        "id": "G105-3",
        "name": 'G105-3',
        "type": "Medium Van",
        "size": "4525*1610*190",
        "GVW": "2.5T",
        "Battery": "41.86kWh",
        "Range": "252km",
        "slideImg": `${CDN_URL}/resource/products/slide_G105-3.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G105-3.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G105-3.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G105-3.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G105.mp4`,
      },
      {
        "id": "G050-L",
        "name": 'G050-L',
        "type": "Small Van",
        "size": "3395*1475*1950",
        "GVW": "1.67T",
        "Battery": "29.67kWh",
        "Range": "162km",
        "slideImg": `${CDN_URL}/resource/products/slide_G050-L.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G050-L.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G050-L.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G050-L.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G050.mp4`,
      },
    ]
  },
  {
    "id": 'e-Light_Truck',
    "name": 'e-Light Truck',
    "menuType": 'group',
    "children": [
      {
        "id": "E-STAR_T",
        "name": 'E-STAR T',
        "type": "Medium Truck",
        "size_with_box": "5750*1770*2670",
        "size_chassis": "5500*1650*1750",
        "GVW": "3.5T",
        "Battery": "66.8kWh",
        "Range": "250km",
        "slideImg": `${CDN_URL}/resource/products/slide_E-STAR_T.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_E-STAR_T.webp`,
        "outlightImg": `${CDN_URL}/resource/products/product_sub_E-STAR_T.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_E-STAR_T.webp`,
        "formImg": `${CDN_URL}/resource/products/product_E-STAR_T.webp`,
        "videoSrc": `${CDN_URL}/resource/video/T.mp4`,
      },
      {
        "id": "G050P-L",
        "name": 'G050P-L',
        "type": "Small Truck",
        "size": "3695*1475*1980",
        "GVW": "1.6T",
        "Battery": "29.67kWh",
        "Range": "210km",
        "slideImg": `${CDN_URL}/resource/products/slide_G050P-L.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_G050P-L.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_G050P-L.webp`,
        "formImg": `${CDN_URL}/resource/products/product_G050P-L.webp`,
        "videoSrc": `${CDN_URL}/resource/video/G050.mp4`,
      },
    ]
  },
  {
    "id": 'e-Tractor',
    "name": 'e-Tractor',
    "menuType": 'group',
    "children": [
      {
        "id": "Sany_SE636",
        "name": 'Sany SE636',
        "type": "e-Tractor",
        "size": "6890*2545*3870",
        "Battery": "636kWh",
        "Range": "500km",
        "L2": "AEB/LKA/LCC/LDW/FCW/DMS/360° Camera ",
        "slideImg": `${CDN_URL}/resource/products/slide_Sany_SE636.webp`,
        "bannerImg": `${CDN_URL}/resource/products/product_Sany_SE636.webp`,
        "infoTable": `${CDN_URL}/resource/products/product_detail_Sany_SE636.webp`,
        "formImg": `${CDN_URL}/resource/products/product_Sany_SE636.webp`,
        "videoSrc": `${CDN_URL}/resource/video/Sany_SE636.mp4`,
      },
    ]
  },
];
export const brandsListData = [
  {
    id: 'wuling',
    name: 'wuling',
    logo: `${CDN_URL}/resource/images/logo_wuling.png`,
    logo_color: `${CDN_URL}/resource/images/logo_wuling_color.webp`,
    cover_sm: `${CDN_URL}/resource/images/cover_wuling_sm.webp`,
    cover_lg: `${CDN_URL}/resource/images/cover_wuling_lg.webp`,
    poster: `${CDN_URL}/resource/images/poster_wuling.webp`,
    video: `${CDN_URL}/video/wuling.mp4`,
    content: [
      'Wuling Motors Holdings Limited is a Hong Kong listed company that focuses on the automotive industry business,and the Stock Abbreviation : Wuling Motors, stock code is 00305.HK. HK.The company inherits nearly a century of manufacturing experience from the controlling shareholder Guangxi Automotive Group, focusing on the design, research and development, and manufacturing of automotive components, automotive power systems, and commercial vehicles which includes new energy logistics vehicles.',
      "It provides high-value component products to over 40 Automobile manufacturer, power systems to over 10 million terminal client, and To provide more than 1 million users with quality and suitable vehicle and travel services. Currently, we have production bases in Liuzhou, Qingdao, Chongqing, Jingmen, Nanning, Indonesia, and India. We are a National High-Tech Enterprise and ranked among China's Top 100 Automotive Supply Chain Enterprises.",
    ]
  },
  {
    id: 'dongfeng',
    name: 'dongfeng',
    logo: `${CDN_URL}/resource/images/logo_dongfeng.png`,
    logo_color: `${CDN_URL}/resource/images/logo_dongfeng_color.svg`,
    cover_sm: `${CDN_URL}/resource/images/cover_dongfeng_sm.webp`,
    cover_lg: `${CDN_URL}/resource/images/cover_dongfeng_lg.webp`,
    poster: `${CDN_URL}/resource/images/poster_dongfeng.webp`,
    video: `${CDN_URL}/video/dongfeng.mp4`,
    content: [
      "Dongfeng Motor Corporation Limited is a significant backbone of China's automotive industry. Its predecessor, the Second Automobile Manufacturing Plant, was established in 1969. The company is headquartered in Wuhan, Hubei Province. It currently has total assets of 499.3 billion yuan and employs 127,000 people, ranked 188nd in the world's top 500. It has sold over 1,200,000 vehicles overseas, with its products sold in over 100 countries.",
    ]
  },
  {
    id: 'sany',
    name: 'sany',
    logo: `${CDN_URL}/resource/images/logo_sany.svg`,
    logo_color: `${CDN_URL}/resource/images/logo_sany_color.svg`,
    cover_sm: `${CDN_URL}/resource/images/cover_sany_sm.webp`,
    cover_lg: `${CDN_URL}/resource/images/cover_sany_lg.webp`,
    poster: `${CDN_URL}/resource/images/poster_sany.webp`,
    video: `${CDN_URL}/resource/video/sany.mp4`,
    content: [
      "Since 1989, SANY’s vision to build a first-class enterprise, to foster first-class employees, and to make first-class contributions to society has never wavered.We have focused on delivering value to customers, employees, shareholders, and the public by offering high-quality products and services,providing a work environment full of opportunities, releasing financial reports to meet investor expectations, and exerting our own influence to help those in need.",
      "In the past three decades, we have expanded our business to a wide range of areas, including construction and mining equipment, port machinery, oil drilling machinery, and renewable wind energy systems. We keep exploring more possibilities to expand our reach and innovate our way of doing business as well as to raise the standard and answer the call for new market needs",
      "SANY is a forward-looking company that was born in a time of change and now looks for any opportunity in those changes that will lead the way to the future. We are unleashing the power of data in the connectivity of machines, realizing smart manufacturing and autonomous operation with some models.The efforts to add a new electric product portfolio makes SANY stand out in today’s digital world and is also part of our sustainable solutions."
    ]
  },
];